### ISSUE TITLE
Request (Not an Issue): Xamarin Forms Support

### ISSUE THREAD

**Issue by Nickprovs** [Rychu-Pawel/NumericalLibraries#1]
Hey Rychu,

I'm writing an application that simulates gravitational waves in Xamarin Forms. A graph and sound are generated based on user parameter input. For some simulations, I can do everything algebraically. But for others, I need to use ODE's.

I would love to use your library if possible but it doesn't seem like I can. I get this error when trying to install the package to my solution.

Error: Could not install package 'Rychusoft.NumericalLibraries.Calculator 1.0.6216.39191'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any chance you will support Xamarin in the future?

Best,

Nick

**Comment by Rychu-Pawel** [comment]
Hey,
Sounds like a cool project. Are you going to use it for time travel and teleportation? Just joking... :)
Looks like recompiling with targeting .Net Standard should help. Give me a second.

**Comment by Rychu-Pawel** [comment]
Hi again @Nickprovs ,

First of all thanks for choosing my library :)

I managed to retarget the Calculator library to .Net Standard 1.1 (there's a reference to System.Numerics and System.Drawings there that are available starting from v1.1). This should let you reference it from Xamarin and .Net Core projects. It's available on nuget: https://www.nuget.org/packages/Rychusoft.NumericalLibraries.Calculator/1.1.0

I only managed to retarget the Calculator for now as I'm a bit busy working on other project right now but if you need something else from the suite (chart, derivatives, differentials etc.) then just let me know and I'll try to retarget them and publish to nuget as well.

Let me know if it works.

Cheers!

Regards
Rychu

**Comment by Nickprovs** [comment]
@Rychu-Pawel,

Holy crap! I've never had somebody respond so quickly before. Thanks so much. My primary interest in the library is using it to solve some differential equations. If differentials can be re-targeted (and by extension, the derivatives (I imagine)), then that would be amazing.

I'd totally understand if that's not possible or if it takes you a while to get to. 

I would of course credit you and your library if you like how my app turns out. It's being made in association a with LIGO physicist.

Worst case, there's another ODE solver called OSLO by a Microsoft researcher I can use but it's been giving me troubles.

Edit: It wont be able to time-travel but it'll make neat sounds. https://www.soundsofspacetime.org/elliptical-binaries.html

Best,

Nick

**Comment by Rychu-Pawel** [comment]
This LIGO? Well... sounds like some serious stuff ;)
If that's the case then I'll retarget them this week. I'll try to do this today after work.

**Comment by Rychu-Pawel** [comment]
Hello there @Nickprovs ,

How are you today? :)

All the instruments are ready and prepared. Differentials and derivatives are in place (ensure you use 1.1.0 version):
**https://www.nuget.org/packages/Rychusoft.NumericalLibraries.Differential**
https://www.nuget.org/packages/Rychusoft.NumericalLibraries.Derivative

 Let's hear some space sounds! :)

Hope everything will go well. Fingers crossed and good luck. May the dark matter be with you!

Feel free to come back in case of any issues.

Regards,
Rychu

PS. Please remember about my credits :) Not often you are a part of something cool.
PS2. Normally I'm very modest 👍

**Comment by Nickprovs** [comment]
@Rychu-Pawel

Absolutely! Your generosity will not be forgotten :). I have some finals coming up at school but I will begin working with it soon. I'll keep you posted!

Best,

Nick
